suggested nav fix for register
Liryvian/ft_transcendence pull request #182
Opened 2023-03-02 16:23 UTC by Ryno95

You know ;)

2023-03-02 16:49 UTC, vincentvis requested changes

2023-03-02 18:35 UTC, Ryno95 commented on frontend/src/router/index.ts
> +			],
Yes i forgot to push  :D

2023-03-02 18:46 UTC, vincentvis commented on frontend/src/router/index.ts
> +			],
yes, we assumed something like that :)

2023-03-02 18:46 UTC, vincentvis approved these changes

2023-03-03 08:15 UTC, livlaming approved these changes

2023-03-03 08:39 UTC, merged